<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFojlxqd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFojlxqd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFojlxqd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFojlxqd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFojlxqd\appProdProjectContainer([
    'container.build_hash' => 'Fojlxqd',
    'container.build_id' => '2a859309',
    'container.build_time' => 1721146021,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFojlxqd');
